# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-25 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ftp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='FtpUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=256, verbose_name='\u516c\u53f8\u540d\u5b57')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='\u90ae\u7bb1')),
                ('phone_num', models.CharField(default='138000138000', max_length=15, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('reg_ip', models.GenericIPAddressField(default='127.0.0.1', editable=False, verbose_name='\u7533\u8bf7IP')),
                ('is_active', models.BooleanField(default=False, verbose_name='\u6fc0\u6d3b')),
                ('is_staff', models.BooleanField(default=False, verbose_name='\u767b\u5f55\u7ba1\u7406')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '\u5e10\u6237',
                'verbose_name_plural': '\u5e10\u6237',
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u5e73\u53f0\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5e73\u53f0\u7c7b\u578b',
                'verbose_name_plural': '\u5e73\u53f0\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='FileVer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_name', models.CharField(max_length=256, verbose_name='\u7248\u672c')),
                ('file_name', models.FileField(max_length=1024, upload_to=ftp.models.get_upload_dir, verbose_name='\u6587\u4ef6\u540d')),
                ('commit', models.TextField(max_length=1024, verbose_name='\u5907\u6ce8')),
                ('target_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftp.FileType', verbose_name='\u5e73\u53f0\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u7248\u672c\u5217\u8868',
                'verbose_name_plural': '\u7248\u672c\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u4ea7\u54c1\u540d\u79f0')),
                ('ftp_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u540d')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u7ba1\u7406',
                'verbose_name_plural': '\u4ea7\u54c1\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='filetype',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftp.Product', verbose_name='\u4ea7\u54c1\u540d\u79f0'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('ftp_user', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='filever',
            unique_together=set([('ver_name', 'target_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='filetype',
            unique_together=set([('name', 'product_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='ftpuser',
            unique_together=set([('name', 'email')]),
        ),
    ]
