# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import ftp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': '\u4ea7\u54c1\u7ba1\u7406', 'verbose_name_plural': '\u4ea7\u54c1\u7ba1\u7406'},
        ),
        migrations.AddField(
            model_name='filever',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='filever',
            name='file_name',
            field=models.FileField(help_text='\u6587\u4ef6\u5927\u5c0f\u4e0d\u80fd\u8d85\u8fc710M', max_length=1024, upload_to=ftp.models.get_upload_dir, verbose_name='\u6587\u4ef6\u540d'),
        ),
    ]
