# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0002_auto_20160330_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpuser',
            name='last_touch',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6ce8\u518c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='filever',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
