# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0003_auto_20160330_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftpuser',
            name='last_touch',
        ),
    ]
